# Website Summarizer Configuration Templates

# Configuration for different website types
website_types:
  restaurant:
    priority_pages: ['homepage', 'about', 'menu/services', 'contact']
    key_fields:
      - name
      - cuisine_type
      - location
      - phone
      - opening_hours
      - specialties
    content_patterns:
      name: ['ristorante', 'pizzeria', 'trattoria', 'osteria']
      location: ['via', 'corso', 'piazza', 'viale']
      phone: ['\d{3}[\.-]?\d{3}[\.-]?\d{4}', '\+39', '0\d{2,4}']
      hours: ['orari', 'aperto', 'chiuso', 'ore']
    
  ecommerce:
    priority_pages: ['homepage', 'about', 'products', 'contact']
    key_fields:
      - company_name
      - products
      - shipping_info
      - payment_methods
      - contact_info
    content_patterns:
      products: ['prodotti', 'catalogo', 'shop', 'store']
      shipping: ['spedizione', 'consegna', 'shipping']
      payment: ['pagamento', 'payment', 'carta']
  
  corporate:
    priority_pages: ['homepage', 'about', 'services', 'contact', 'news/blog']
    key_fields:
      - company_name
      - services
      - mission
      - team
      - location
      - contact_info
    content_patterns:
      services: ['servizi', 'services', 'soluzioni']
      mission: ['missione', 'vision', 'valori']
      team: ['team', 'staff', 'chi siamo']
  
  portfolio:
    priority_pages: ['homepage', 'about', 'gallery', 'contact']
    key_fields:
      - name
      - profession
      - skills
      - portfolio_items
      - contact_info
    content_patterns:
      skills: ['competenze', 'skills', 'expertise']
      portfolio: ['portfolio', 'lavori', 'progetti']

# Analysis settings
analysis:
  min_word_count: 10  # Minimum words to consider a page
  max_summary_length: 200
  min_summary_length: 50
  key_phrases_count: 10
  
# Content extraction patterns
extraction_patterns:
  email: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
  phone_italian: '(?:\+39|0039)?\s?(?:\d{2,4})\s?(?:\d{6,8})'
  phone_international: '(?:\+\d{1,3})?\s?\(?(?:\d{3})\)?\s?(?:\d{3})\s?(?:\d{4})'
  address_keywords: ['via', 'corso', 'piazza', 'viale', 'strada', 'street', 'avenue', 'road']
  
# Page classification rules
page_classification:
  homepage:
    url_patterns: ['/', 'home', 'index', 'homepage']
    title_patterns: ['home', 'benvenuti', 'welcome']
    content_patterns: ['benvenuti', 'welcome', 'homepage']
    
  about:
    url_patterns: ['about', 'chi-siamo', 'about-us', 'storia', 'azienda']
    title_patterns: ['about', 'chi siamo', 'storia', 'azienda']
    content_patterns: ['storia', 'fondata', 'established', 'mission']
    
  contact:
    url_patterns: ['contact', 'contatti', 'contatto']
    title_patterns: ['contact', 'contatti']
    content_patterns: ['telefono', 'email', 'indirizzo', 'phone']
    
  menu_services:
    url_patterns: ['menu', 'carta', 'servizi', 'products', 'catalogo']
    title_patterns: ['menu', 'carta', 'servizi', 'prodotti']
    content_patterns: ['€', '$', 'prezzo', 'price']
    
  gallery:
    url_patterns: ['gallery', 'galleria', 'foto', 'images', 'portfolio']
    title_patterns: ['gallery', 'galleria', 'foto']
    content_patterns: ['immagini', 'foto', 'gallery']
    
  news_blog:
    url_patterns: ['news', 'blog', 'articoli', 'notizie', 'eventi']
    title_patterns: ['news', 'blog', 'articoli', 'notizie']
    content_patterns: ['pubblicato', 'posted', 'data', 'articolo']
    
  legal:
    url_patterns: ['privacy', 'cookie', 'terms', 'legal', 'condizioni']
    title_patterns: ['privacy', 'cookie', 'terms', 'condizioni']
    content_patterns: ['privacy', 'cookie', 'gdpr', 'termini']

# Output formatting
output:
  report_sections:
    - general_stats
    - page_types
    - contact_info
    - navigation
    - key_phrases
    - content_summary
    - largest_page
  
  export_formats:
    - json
    - txt
    - html